title: "Blog | Rafael"
description: "Pasionate Software Developer at Corotos and creator of Hauzzy. Here I share notes I take along the way."
url: 'https://rafaelmontas.com'
repository: rafaelmontas/rafaelmontas.github.io
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss
postcss:
  cache: false
permalink: /:categories/:title/
feed:
  path: /feed.atom
