theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss
postcss:
  cache: false
permalink: /:categories/:title/
excerpt_separator: <!--more-->
baseurl: /
url: https://rafaelmontas.github.io