url: 'https://rafaelmontas.com'
repository: rafaelmontas/rafaelmontas.github.io
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss
postcss:
  cache: false
permalink: /:categories/:title/
