title: "Blog Rafael"
description: "Passionate Software Developer. Currently improving my Ruby/Rails skills every signle day and sharing what I learn."
url: 'https://www.rafaelmontas.com'
baseurl: ''
repository: rafaelmontas/rafaelmontas.github.io
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/default-card.png
theme: null
timezone: America/Santo_Domingo
google_analytics: G-M8XVM0T71Y
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss
postcss:
  cache: false
permalink: /:categories/:title/
twitter:
  username: rmontas
  card: 'summary_large_image'
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
